language: clojure
lein: lein
script: "lein do compile, spec"
matrix:
  include:
    - addons:
        apt:
          packages:
            - openjdk-6-jdk
      jdk: openjdk6
    - openjdk7
    - openjdk8
    - oraclejdk8
    - oraclejdk9
    - oraclejdk11
